import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./apigen"; // generated by openapi-typescript

const envBaseUrl = import.meta.env.VITE_WORKFLOW_API_BASE_URL as string | undefined;
const defaultPort = (import.meta.env.VITE_WORKFLOW_API_PORT as string | undefined) || "8008";
const browserApiPortBaseUrl =
  typeof window !== "undefined"
    ? `${window.location.protocol}//${window.location.hostname}:${defaultPort}`
    : `http://localhost:${defaultPort}`;
const inferredBrowserBaseUrl =
  typeof window !== "undefined"
    ? window.location.port === "5173"
      ? browserApiPortBaseUrl
      : window.location.origin
    : browserApiPortBaseUrl;
const baseUrl =
  envBaseUrl && envBaseUrl.trim().length > 0 ? envBaseUrl : inferredBrowserBaseUrl;

export const fetchClient = createFetchClient<paths>({
  baseUrl,
});

export const $api = createClient(fetchClient);

export default $api;
